import type { Project, Experience, Education, Achievement } from "@/types";

export const profile = {
  name: "JOSHUA APOLLO",
  tagline: "Computer Engineering student at NTU specialising in systems security and AI infrastructure.",
  objective: "Seeking to apply full-stack and distributed systems experience to security or cloud engineering teams.",
  email: "joshua.apollo13@gmail.com",
  github: "github.com/theApolloAlien",
  linkedin: "linkedin.com/in/Joshua-Apollo",
};

export const skills = {
  languages: ["Python", "SQL", "C/C++", "Java", "JavaScript", "Assembly (MIPS/x86)"],
  frameworks: ["Flutter", "FastAPI", "ChromaDB", "Burp Suite", "Metasploit", "RESTful APIs", "Android Studio"],
  domains: ["Retrieval-Augmented Generation (RAG)", "Offensive Security", "Application Security"],
  platforms: ["iOS Development", "Linux", "Azure"],
};

export const projects: Project[] = [
  {
    id: "macropolo",
    title: "MacroPollo",
    subtitle: "Autonomous Research Agent",
    year: "2026",
    badge: "TOP 8 · NTU FINTECH INNOVATORS HACKATHON 2026",
    link: "https://youtu.be/5SY_k4d-_w4?si=ufwPUOpSZMF9R7q4",
    stack: ["ChromaDB", "RAG", "LLM"],
    bullets: [
      "Built a custom AI agent that automates data synthesis from multiple unstructured sources, applying advanced prompt engineering and LLM orchestration to generate actionable analytical insights in real-time, analogous to building custom Gemini Gems for automated reporting.",
      "Designed structured evaluation pipelines to benchmark output accuracy, iteratively refining prompt strategies to improve the reliability and precision of AI-generated analysis.",
      "Delivered a polished end-to-end demo placing Top 8 at NTU's Fintech Innovators Hackathon 2026.",
    ],
  },
  {
    id: "clinic-ai",
    title: "CLINIC AI",
    subtitle: "Multimodal AI Triage Agent",
    year: "2026",
    stack: ["Python", "Computer Vision", "Audio Processing", "Generative AI"],
    bullets: [
      "Built an AI-driven data processing pipeline that fuses multiple real-time data streams (vision, audio, physiological signals), automating classification and generating prioritised outputs within 10 seconds.",
      "Designed the system as a replicable proof-of-concept with documented workflows, enabling rapid iteration and continuous improvement of data collection and analysis processes.",
    ],
  },
  {
    id: "rail-energy",
    title: "Rail Energy System",
    subtitle: "SBS Transit Hackathon",
    year: "2026",
    badge: "NATIONAL WINNER · 1ST PLACE · SGD 3,000 · 200+ TEAMS",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7426624723855405056/",
    stack: ["Energy Harvesting", "Hardware Prototyping", "Systems Design"],
    bullets: [
      "Proposed a novel energy-harvesting system that captures the piston-effect airflow generated by trains passing through underground MRT stations, using turbines to convert this otherwise-wasted tunnel wind into usable electrical energy.",
      "Designed and built a working prototype that validated the concept's technical viability.",
    ],
  },
  {
    id: "pillpollo",
    title: "PillPollo",
    subtitle: "AI Clinical Intelligence Platform",
    year: "2026",
    badge: "TOP 50 · NTU CHUA THIAN POH PINNACLE PRIZE 2026",
    stack: ["Product Strategy", "Go-to-Market", "Healthcare SaaS"],
    bullets: [
      "Designed a technology-driven product for healthcare, defining the product vision, technical architecture, and go-to-market strategy including SaaS pricing, market sizing, and a mapped procurement pathway.",
    ],
  },
];

// Ordered so cybersecurity roles sit at the top (most prominent), then the
// remaining roles most-recent-first.
export const experience: Experience[] = [
  {
    title: "Cybersecurity Intern (Pentesting & AI Security)",
    org: "PwC (PricewaterhouseCoopers)",
    period: "Jul 2026 – Dec 2026",
    bullets: [
      "Joining the cybersecurity team with a focus on penetration testing and red teaming, AI security, and automation of cybersecurity workflows using AI-native tooling.",
    ],
  },
  {
    title: "Cybersecurity Intern & Cyber Tools Researcher",
    org: "Thinkture",
    period: "Apr 2021 – Feb 2022",
    bullets: [
      "Built custom Python tooling to automate detection and scanning of all OWASP Top 10 vulnerabilities, reducing manual security audit time across client engagements.",
      "Engineered a ransomware proof-of-concept in a controlled lab environment to simulate advanced persistent threat (APT) evasion behaviour, used to stress-test and harden client infrastructure.",
      "Executed mobile and network penetration tests using Burp Suite and Metasploit; translated discovered vulnerabilities into prioritised, business-impact-focused remediation reports for clients.",
    ],
  },
  {
    title: "Independent Creator & Partnerships Lead",
    org: "YouTube",
    period: "Aug 2024 – Mar 2025",
    bullets: [
      "Managed 30+ end-to-end production projects for international partners including Uppbeat and Dehancer.",
    ],
  },
  {
    title: "Firefighting Trainer, Sergeant",
    org: "Singapore Civil Defence Force",
    period: "Oct 2022 – Aug 2024",
    bullets: [
      "2-Year Mandatory Service. Awarded the 2024 Good Performance Award for sustained operational excellence.",
    ],
  },
];

export const education: Education[] = [
  {
    institution: "Nanyang Technological University (NTU)",
    degree: "B.Comp (Hons) Computer Engineering",
    gpa: "4.4 / 5",
    period: "Aug 2025 – 2028",
  },
  {
    institution: "Ngee Ann Polytechnic",
    degree: "Diploma in Cybersecurity",
    gpa: "3.65 / 4",
    period: "Apr 2019 – May 2022",
  },
];

export const achievements: Achievement[] = [
  {
    title: "International CTF Representative",
    org: "NTU Sentinels",
    year: "2025",
    description: "Selected to represent NTU at the Vietnam National Cybersecurity Association CTF, competing against university teams internationally.",
  },
  {
    title: "Subcommittee Member",
    org: "NTU Sentinels Cybersecurity Club",
    year: "2025 – Present",
    description: "Co-led planning of SentCTF, NTU's flagship cybersecurity competition; coordinated cross-functional teams and drove industry partnership outreach.",
  },
  {
    title: "Chief Group Leader & Student Ambassador",
    org: "CCDS Orientation, NTU",
    year: "2025 – Present",
    description: "Commanded a committee of 10 student leaders across large-scale orientation events, maintaining 100% safety compliance across all operational timelines.",
  },
  {
    title: "President",
    org: "Debate Society",
    year: "Jan 2017 – Mar 2018",
    description: "Multiple 'Best Speaker' awards for constructing rigorous, policy-driven arguments under competitive pressure.",
  },
];

export const coursework = [
  "Data Structures & Algorithms",
  "Operating Systems",
  "Computer Networks",
  "Software Engineering",
  "Object-Oriented Programming",
  "Ethical Hacking",
  "Databases",
  "Cryptography",
  "Malware Analysis",
  "Front-End Development",
];
